### ISSUE TITLE
Tomo-chan Integration

### ISSUE THREAD

**Issue by jaygradon** [rarskal/ScampBot#15]
## What

**Scope:** User Functions
**Description:** Add integration with read.tomochan.today

**Criteria:**
 - [ ] Get latest tomo-chan: [Issue](https://github.com/rarskal/ScampBot/issues/7)
 - [ ] Is there a tomo-chan today?: [Issue](https://github.com/rarskal/ScampBot/issues/14)
 - [ ] Get tomo-chan by number: [Issue](https://github.com/rarskal/ScampBot/issues/12)
 - [ ] Get random tomo-chan: [Issue](https://github.com/rarskal/ScampBot/issues/13)

## Why

Because I read tomo-chan

## Who Needs to Know?

@rarskal

**Comment by jaygradon** [comment]
Iced indefinitely due to translation sourcing uncertainties.
