### ISSUE TITLE
Mount&Blade Trade Index

### ISSUE THREAD

**Issue by jaygradon** [rarskal/ScampBot#18]
## What

**Scope:** User Functions
**Description:** Create an index for tracking trade prices for the game Mount&Blade Warband and Bannerlord.

**Criteria:**
 - [x] Create/switch index
 - [x] Add Good to index
 - [x] Add Location to track goods for to index
 - [x] Update data in index (by good/location)
 - [x] Retrieve data from index (by good) as table
 - [x] Track true value, highest/lowest value, and recommended buy/sell price of goods
 - [ ] Recommend locations to buy/sell a good

## Why

Tracking prices in M&B is essential for trading and is a PITA to figure out.  Maintaining spreadsheets is a hassle.

## Who Needs to Know?

@rarskal
