### ISSUE TITLE
Giphy Integration

### ISSUE THREAD

**Issue by jaygradon** [rarskal/ScampBot#3]
## What

**Scope:**  Programmer Functions and User Features  
**Description:** Add ScampBot integration with Giphy API  

**Criteria**:  
 - [x] Allow ScampBot to get a given gif from Giphy: [Issue](https://github.com/rarskal/ScampBot/issues/2), [PR](https://github.com/jaygradon/ScampBot/pull/6)
 - [x] Allow ScampBot to search for a suitable gif from Giphy: [Issue](https://github.com/rarskal/ScampBot/issues/4), [PR](https://github.com/rarskal/ScampBot/pull/11)
 - [x] Allow user to ask for a trending gifs from Giphy: [Issue](https://github.com/rarskal/ScampBot/issues/10), [PR](https://github.com/rarskal/ScampBot/pull/16)
 - [ ] Have a library of manually vetted and labelled quality gifs as reference: [Issue](https://github.com/rarskal/ScampBot/issues/5)

## Why

Allow responses to include gifs and allow for querying giphy

## Who Needs to Know?

@rarskal
